// src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const count = ref(0);

onMounted(() => {
  let script = document.createElement("script");
  script.setAttribute("type", "module");
  script.setAttribute("src", "/distReact/some-react-component.js");
  document.head.appendChild(script);
});
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <button type="button" @click="count++">
    Vue Button: count is {{ count }}
  </button>
  <custom-react :value="count" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// reactComponent/src/App.jsx
import reactLogo from "./assets/react.svg";
import viteLogo from "../../public/vite.svg";

function App(props) {
  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => props.setValue(parseInt(props.value) + 1)}>
          React button: count is {props.value}
        </button>
      </div>
    </div>
  );
}

export default App;
